### ISSUE TITLE
Drafts are not hidden from side bar

### ISSUE THREAD

**Issue by osterman** [cloudposse/docs#7]
## what
* Drafts should not appear in the left-sidebar

## why
* Confusing documentation

**Comment by finnsky** [comment]
not really sure what means "drafts in sidebar"

**Comment by aknysh** [comment]
@finnsky 
`drafts in sidebar` are these:
https://github.com/cloudposse/docs/blob/master/content/other-saas/quip.md
https://raw.githubusercontent.com/cloudposse/docs/master/content/other-saas/quip.md

and the issue is, if `draft: true`, the page should not be shown in the menu, but they are shown now
